[parameters.history_length]
min = 32
max = 144
step = 8
log = false

[parameters.units]
min = 64
max = 384
step = 8
log = false

[parameters.num_layers]
min = 2
max = 10
step = 2
log = false

[parameters.dropout]
min = 0.2
max = 0.5
log = false

[parameters.batch_size]
min = 64
max = 384
step = 4
log = false

[parameters.learning_rate]
min = 0.0002
max = 0.002
log = true

[parameters.weight_decay]
min = 0.0001
max = 0.01
log = true
