[parameters.mid_layer_count]
min = 2
max = 5
step = 1
log = false

[parameters.mid_layer_size]
min = 128
max = 512
step = 64
log = false

[parameters.dropout]
min = 0.05
max = 0.4
log = true

[parameters.batch_size]
min = 64
max = 256
step = 16
log = false

[parameters.learning_rate]
min = 0.0001
max = 0.003
log = true

[parameters.weight_decay]
min = 0.00001
max = 0.01
log = true