[model]
type = "MLP"
name = "mlp_regressor"

hidden_layers = [64, 64]
dropout = 0.1

[training]
max_epochs = 20
batch_size = 128
learning_rate = 0.001
weight_decay = 0.0
patience = 50
seed = 42

[data]
train_csv = "/home/amoris/dbps/data-analysis-on-DBPs/uploads/splits/2d927a7b-fc13-4bf2-b1ef-87c26e0ac331/train.csv"
val_csv = "/home/amoris/dbps/data-analysis-on-DBPs/uploads/splits/2d927a7b-fc13-4bf2-b1ef-87c26e0ac331/val.csv"
test_csv = "/home/amoris/dbps/data-analysis-on-DBPs/uploads/splits/2d927a7b-fc13-4bf2-b1ef-87c26e0ac331/test.csv"
input_columns = ["TRC-DT", "pH-DT", "cond-DT", "TRC-RT", "pH-RT"]
output_columns = ["TRC-PPL1", "TRC-PPL2"]
