[model]
type = "MLP"
name = "mlp_model"

hidden_layers = [64, 64]
dropout = 0.1

[training]
max_epochs = 3
batch_size = 64
learning_rate = 0.001
weight_decay = 0.0
patience = 50
seed = 42

[data]
train_csv = "/home/amoris/dbps/data-analysis-on-DBPs/uploads/splits/d5e6d3bc-5087-41a6-a526-8df42fa3fe40/train.csv"
val_csv = "/home/amoris/dbps/data-analysis-on-DBPs/uploads/splits/d5e6d3bc-5087-41a6-a526-8df42fa3fe40/val.csv"
test_csv = "/home/amoris/dbps/data-analysis-on-DBPs/uploads/splits/d5e6d3bc-5087-41a6-a526-8df42fa3fe40/test.csv"
input_columns = ["TRC-DT", "pH-DT"]
output_columns = ["TRC-PPL1"]
