[model]
type = "MLP"
name = "mlp_model"

hidden_layers = [64, 64]
dropout = 0.1

[training]
max_epochs = 3
batch_size = 64
learning_rate = 0.001
weight_decay = 0.0
patience = 50
seed = 42

[data]
train_csv = "/home/amoris/dbps/data-analysis-on-DBPs/uploads/splits/2c0b7a02-8069-4d2e-869c-009a94ffd93c/train.csv"
val_csv = "/home/amoris/dbps/data-analysis-on-DBPs/uploads/splits/2c0b7a02-8069-4d2e-869c-009a94ffd93c/val.csv"
test_csv = "/home/amoris/dbps/data-analysis-on-DBPs/uploads/splits/2c0b7a02-8069-4d2e-869c-009a94ffd93c/test.csv"
input_columns = ["TRC-DT", "pH-DT", "cond-DT"]
output_columns = ["TRC-PPL1", "pH-PPL1"]
